# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.auth_api import AuthApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_jwt_session(self):
        """Test case for jwt_session

        """
        pass

    def test_login(self):
        """Test case for login

        """
        pass

    def test_login1(self):
        """Test case for login1

        """
        pass

    def test_logout(self):
        """Test case for logout

        """
        pass

    def test_password_recovery(self):
        """Test case for password_recovery

        """
        pass

    def test_qr_code_recovery(self):
        """Test case for qr_code_recovery

        """
        pass

    def test_recover_password(self):
        """Test case for recover_password

        """
        pass

    def test_recover_qr_code(self):
        """Test case for recover_qr_code

        """
        pass

    def test_register1(self):
        """Test case for register1

        """
        pass

    def test_service_login(self):
        """Test case for service_login

        """
        pass

    def test_service_logout(self):
        """Test case for service_logout

        """
        pass

    def test_session(self):
        """Test case for session

        """
        pass

    def test_validate_password_recovery(self):
        """Test case for validate_password_recovery

        """
        pass

    def test_validate_user_mail(self):
        """Test case for validate_user_mail

        """
        pass


if __name__ == '__main__':
    unittest.main()
