# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.model_inference_service_api import ModelInferenceServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelInferenceServiceApi(unittest.TestCase):
    """ModelInferenceServiceApi unit test stubs"""

    def setUp(self):
        self.api = api.model_inference_service_api.ModelInferenceServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_infer(self):
        """Test case for infer

        Make inference  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
