# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.hopssite_service_api import HopssiteServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHopssiteServiceApi(unittest.TestCase):
    """HopssiteServiceApi unit test stubs"""

    def setUp(self):
        self.api = api.hopssite_service_api.HopssiteServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_comment(self):
        """Test case for add_comment

        """
        pass

    def test_add_dataset_issue(self):
        """Test case for add_dataset_issue

        """
        pass

    def test_add_rating(self):
        """Test case for add_rating

        """
        pass

    def test_delete_comment(self):
        """Test case for delete_comment

        """
        pass

    def test_get_all_comments(self):
        """Test case for get_all_comments

        """
        pass

    def test_get_all_datasets(self):
        """Test case for get_all_datasets

        """
        pass

    def test_get_cluster_id(self):
        """Test case for get_cluster_id

        """
        pass

    def test_get_dataset(self):
        """Test case for get_dataset

        """
        pass

    def test_get_display_categories(self):
        """Test case for get_display_categories

        """
        pass

    def test_get_local_dataset(self):
        """Test case for get_local_dataset

        """
        pass

    def test_get_rating(self):
        """Test case for get_rating

        """
        pass

    def test_get_service_info(self):
        """Test case for get_service_info

        """
        pass

    def test_get_user_id(self):
        """Test case for get_user_id

        """
        pass

    def test_report_abuse(self):
        """Test case for report_abuse

        """
        pass

    def test_update_comment(self):
        """Test case for update_comment

        """
        pass


if __name__ == '__main__':
    unittest.main()
