# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.monitor_cluster_service_api import MonitorClusterServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMonitorClusterServiceApi(unittest.TestCase):
    """MonitorClusterServiceApi unit test stubs"""

    def setUp(self):
        self.api = api.monitor_cluster_service_api.MonitorClusterServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_roles(self):
        """Test case for get_all_roles

        """
        pass

    def test_get_host_roles(self):
        """Test case for get_host_roles

        """
        pass

    def test_get_hosts(self):
        """Test case for get_hosts

        """
        pass

    def test_get_hosts1(self):
        """Test case for get_hosts1

        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        """
        pass

    def test_get_service_roles(self):
        """Test case for get_service_roles

        """
        pass

    def test_service_on_host_op(self):
        """Test case for service_on_host_op

        """
        pass

    def test_service_op(self):
        """Test case for service_op

        """
        pass

    def test_service_op1(self):
        """Test case for service_op1

        """
        pass


if __name__ == '__main__':
    unittest.main()
