# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.system_commands_for_kagent_to_execute_or_report import SystemCommandsForKagentToExecuteOrReport  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemCommandsForKagentToExecuteOrReport(unittest.TestCase):
    """SystemCommandsForKagentToExecuteOrReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemCommandsForKagentToExecuteOrReport(self):
        """Test SystemCommandsForKagentToExecuteOrReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.system_commands_for_kagent_to_execute_or_report.SystemCommandsForKagentToExecuteOrReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
