# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.schema_dto import SchemaDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestSchemaDTO(unittest.TestCase):
    """SchemaDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSchemaDTO(self):
        """Test SchemaDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.schema_dto.SchemaDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
