/*
 * Hopsworks api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FeaturestoreClientSettingsDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-11-28T02:09:19.386+01:00[Europe/Stockholm]")public class FeaturestoreClientSettingsDTO {

  @SerializedName("featurestoreStatisticsMaxCorrelations")
  private Integer featurestoreStatisticsMaxCorrelations = null;

  @SerializedName("featurestoreRegex")
  private String featurestoreRegex = null;

  @SerializedName("storageConnectorNameMaxLength")
  private Integer storageConnectorNameMaxLength = null;

  @SerializedName("storageConnectorDescriptionMaxLength")
  private Integer storageConnectorDescriptionMaxLength = null;

  @SerializedName("jdbcStorageConnectorConnectionstringMaxLength")
  private Integer jdbcStorageConnectorConnectionstringMaxLength = null;

  @SerializedName("jdbcStorageConnectorArgumentsMaxLength")
  private Integer jdbcStorageConnectorArgumentsMaxLength = null;

  @SerializedName("s3StorageConnectorBucketMaxLength")
  private Integer s3StorageConnectorBucketMaxLength = null;

  @SerializedName("s3StorageConnectorAccesskeyMaxLength")
  private Integer s3StorageConnectorAccesskeyMaxLength = null;

  @SerializedName("s3StorageConnectorSecretkeyMaxLength")
  private Integer s3StorageConnectorSecretkeyMaxLength = null;

  @SerializedName("s3IAMRole")
  private Boolean s3IAMRole = null;

  @SerializedName("cachedFeaturegroupNameMaxLength")
  private Integer cachedFeaturegroupNameMaxLength = null;

  @SerializedName("cachedFeaturegroupDescriptionMaxLength")
  private Integer cachedFeaturegroupDescriptionMaxLength = null;

  @SerializedName("cachedFeaturegroupFeatureNameMaxLength")
  private Integer cachedFeaturegroupFeatureNameMaxLength = null;

  @SerializedName("cachedFeaturegroupFeatureDescriptionMaxLength")
  private Integer cachedFeaturegroupFeatureDescriptionMaxLength = null;

  @SerializedName("onDemandFeaturegroupNameMaxLength")
  private Integer onDemandFeaturegroupNameMaxLength = null;

  @SerializedName("onDemandFeaturegroupDescriptionMaxLength")
  private Integer onDemandFeaturegroupDescriptionMaxLength = null;

  @SerializedName("onDemandFeaturegroupFeatureNameMaxLength")
  private Integer onDemandFeaturegroupFeatureNameMaxLength = null;

  @SerializedName("onDemandFeaturegroupFeatureDescriptionMaxLength")
  private Integer onDemandFeaturegroupFeatureDescriptionMaxLength = null;

  @SerializedName("onDemandFeaturegroupSqlQueryMaxLength")
  private Integer onDemandFeaturegroupSqlQueryMaxLength = null;

  @SerializedName("trainingDatasetDataFormats")
  private List<String> trainingDatasetDataFormats = null;

  @SerializedName("externalTrainingDatasetNameMaxLength")
  private Integer externalTrainingDatasetNameMaxLength = null;

  @SerializedName("hopsfsTrainingDatasetNameMaxLength")
  private Integer hopsfsTrainingDatasetNameMaxLength = null;

  @SerializedName("trainingDatasetFeatureNameMaxLength")
  private Integer trainingDatasetFeatureNameMaxLength = null;

  @SerializedName("trainingDatasetFeatureDescriptionMaxLength")
  private Integer trainingDatasetFeatureDescriptionMaxLength = null;

  @SerializedName("onDemandFeaturegroupType")
  private String onDemandFeaturegroupType = null;

  @SerializedName("cachedFeaturegroupType")
  private String cachedFeaturegroupType = null;

  @SerializedName("jdbcConnectorType")
  private String jdbcConnectorType = null;

  @SerializedName("hopsfsConnectorType")
  private String hopsfsConnectorType = null;

  @SerializedName("s3ConnectorType")
  private String s3ConnectorType = null;

  @SerializedName("cachedFeaturegroupDtoType")
  private String cachedFeaturegroupDtoType = null;

  @SerializedName("onDemandFeaturegroupDtoType")
  private String onDemandFeaturegroupDtoType = null;

  @SerializedName("hopsfsTrainingDatasetType")
  private String hopsfsTrainingDatasetType = null;

  @SerializedName("externalTrainingDatasetType")
  private String externalTrainingDatasetType = null;

  @SerializedName("hopsfsTrainingDatasetDtoType")
  private String hopsfsTrainingDatasetDtoType = null;

  @SerializedName("externalTrainingDatasetDtoType")
  private String externalTrainingDatasetDtoType = null;

  @SerializedName("trainingDatasetDescriptionMaxLength")
  private Integer trainingDatasetDescriptionMaxLength = null;

  @SerializedName("s3ConnectorDtoType")
  private String s3ConnectorDtoType = null;

  @SerializedName("jdbcConnectorDtoType")
  private String jdbcConnectorDtoType = null;

  @SerializedName("hopsfsConnectorDtoType")
  private String hopsfsConnectorDtoType = null;

  @SerializedName("featuregroupType")
  private String featuregroupType = null;

  @SerializedName("trainingDatasetType")
  private String trainingDatasetType = null;

  @SerializedName("suggestedHiveFeatureTypes")
  private List<String> suggestedHiveFeatureTypes = null;

  @SerializedName("featurestoreUtil4jMainClass")
  private String featurestoreUtil4jMainClass = null;

  @SerializedName("featurestoreUtil4jArgsDataset")
  private String featurestoreUtil4jArgsDataset = null;

  @SerializedName("featurestoreUtilPythonMainClass")
  private String featurestoreUtilPythonMainClass = null;

  @SerializedName("featurestoreUtil4jExecutable")
  private String featurestoreUtil4jExecutable = null;

  @SerializedName("featurestoreUtilPythonExecutable")
  private String featurestoreUtilPythonExecutable = null;

  @SerializedName("s3BucketTrainingDatasetsFolder")
  private String s3BucketTrainingDatasetsFolder = null;

  @SerializedName("featureImportConnectors")
  private List<String> featureImportConnectors = null;

  @SerializedName("onlineFeaturestoreEnabled")
  private Boolean onlineFeaturestoreEnabled = null;

  @SerializedName("suggestedMysqlFeatureTypes")
  private List<String> suggestedMysqlFeatureTypes = null;
  public FeaturestoreClientSettingsDTO featurestoreStatisticsMaxCorrelations(Integer featurestoreStatisticsMaxCorrelations) {
    this.featurestoreStatisticsMaxCorrelations = featurestoreStatisticsMaxCorrelations;
    return this;
  }

  

  /**
  * Get featurestoreStatisticsMaxCorrelations
  * @return featurestoreStatisticsMaxCorrelations
  **/
  @Schema(description = "")
  public Integer getFeaturestoreStatisticsMaxCorrelations() {
    return featurestoreStatisticsMaxCorrelations;
  }
  public void setFeaturestoreStatisticsMaxCorrelations(Integer featurestoreStatisticsMaxCorrelations) {
    this.featurestoreStatisticsMaxCorrelations = featurestoreStatisticsMaxCorrelations;
  }
  public FeaturestoreClientSettingsDTO featurestoreRegex(String featurestoreRegex) {
    this.featurestoreRegex = featurestoreRegex;
    return this;
  }

  

  /**
  * Get featurestoreRegex
  * @return featurestoreRegex
  **/
  @Schema(description = "")
  public String getFeaturestoreRegex() {
    return featurestoreRegex;
  }
  public void setFeaturestoreRegex(String featurestoreRegex) {
    this.featurestoreRegex = featurestoreRegex;
  }
  public FeaturestoreClientSettingsDTO storageConnectorNameMaxLength(Integer storageConnectorNameMaxLength) {
    this.storageConnectorNameMaxLength = storageConnectorNameMaxLength;
    return this;
  }

  

  /**
  * Get storageConnectorNameMaxLength
  * @return storageConnectorNameMaxLength
  **/
  @Schema(description = "")
  public Integer getStorageConnectorNameMaxLength() {
    return storageConnectorNameMaxLength;
  }
  public void setStorageConnectorNameMaxLength(Integer storageConnectorNameMaxLength) {
    this.storageConnectorNameMaxLength = storageConnectorNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO storageConnectorDescriptionMaxLength(Integer storageConnectorDescriptionMaxLength) {
    this.storageConnectorDescriptionMaxLength = storageConnectorDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get storageConnectorDescriptionMaxLength
  * @return storageConnectorDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getStorageConnectorDescriptionMaxLength() {
    return storageConnectorDescriptionMaxLength;
  }
  public void setStorageConnectorDescriptionMaxLength(Integer storageConnectorDescriptionMaxLength) {
    this.storageConnectorDescriptionMaxLength = storageConnectorDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO jdbcStorageConnectorConnectionstringMaxLength(Integer jdbcStorageConnectorConnectionstringMaxLength) {
    this.jdbcStorageConnectorConnectionstringMaxLength = jdbcStorageConnectorConnectionstringMaxLength;
    return this;
  }

  

  /**
  * Get jdbcStorageConnectorConnectionstringMaxLength
  * @return jdbcStorageConnectorConnectionstringMaxLength
  **/
  @Schema(description = "")
  public Integer getJdbcStorageConnectorConnectionstringMaxLength() {
    return jdbcStorageConnectorConnectionstringMaxLength;
  }
  public void setJdbcStorageConnectorConnectionstringMaxLength(Integer jdbcStorageConnectorConnectionstringMaxLength) {
    this.jdbcStorageConnectorConnectionstringMaxLength = jdbcStorageConnectorConnectionstringMaxLength;
  }
  public FeaturestoreClientSettingsDTO jdbcStorageConnectorArgumentsMaxLength(Integer jdbcStorageConnectorArgumentsMaxLength) {
    this.jdbcStorageConnectorArgumentsMaxLength = jdbcStorageConnectorArgumentsMaxLength;
    return this;
  }

  

  /**
  * Get jdbcStorageConnectorArgumentsMaxLength
  * @return jdbcStorageConnectorArgumentsMaxLength
  **/
  @Schema(description = "")
  public Integer getJdbcStorageConnectorArgumentsMaxLength() {
    return jdbcStorageConnectorArgumentsMaxLength;
  }
  public void setJdbcStorageConnectorArgumentsMaxLength(Integer jdbcStorageConnectorArgumentsMaxLength) {
    this.jdbcStorageConnectorArgumentsMaxLength = jdbcStorageConnectorArgumentsMaxLength;
  }
  public FeaturestoreClientSettingsDTO s3StorageConnectorBucketMaxLength(Integer s3StorageConnectorBucketMaxLength) {
    this.s3StorageConnectorBucketMaxLength = s3StorageConnectorBucketMaxLength;
    return this;
  }

  

  /**
  * Get s3StorageConnectorBucketMaxLength
  * @return s3StorageConnectorBucketMaxLength
  **/
  @Schema(description = "")
  public Integer getS3StorageConnectorBucketMaxLength() {
    return s3StorageConnectorBucketMaxLength;
  }
  public void setS3StorageConnectorBucketMaxLength(Integer s3StorageConnectorBucketMaxLength) {
    this.s3StorageConnectorBucketMaxLength = s3StorageConnectorBucketMaxLength;
  }
  public FeaturestoreClientSettingsDTO s3StorageConnectorAccesskeyMaxLength(Integer s3StorageConnectorAccesskeyMaxLength) {
    this.s3StorageConnectorAccesskeyMaxLength = s3StorageConnectorAccesskeyMaxLength;
    return this;
  }

  

  /**
  * Get s3StorageConnectorAccesskeyMaxLength
  * @return s3StorageConnectorAccesskeyMaxLength
  **/
  @Schema(description = "")
  public Integer getS3StorageConnectorAccesskeyMaxLength() {
    return s3StorageConnectorAccesskeyMaxLength;
  }
  public void setS3StorageConnectorAccesskeyMaxLength(Integer s3StorageConnectorAccesskeyMaxLength) {
    this.s3StorageConnectorAccesskeyMaxLength = s3StorageConnectorAccesskeyMaxLength;
  }
  public FeaturestoreClientSettingsDTO s3StorageConnectorSecretkeyMaxLength(Integer s3StorageConnectorSecretkeyMaxLength) {
    this.s3StorageConnectorSecretkeyMaxLength = s3StorageConnectorSecretkeyMaxLength;
    return this;
  }

  

  /**
  * Get s3StorageConnectorSecretkeyMaxLength
  * @return s3StorageConnectorSecretkeyMaxLength
  **/
  @Schema(description = "")
  public Integer getS3StorageConnectorSecretkeyMaxLength() {
    return s3StorageConnectorSecretkeyMaxLength;
  }
  public void setS3StorageConnectorSecretkeyMaxLength(Integer s3StorageConnectorSecretkeyMaxLength) {
    this.s3StorageConnectorSecretkeyMaxLength = s3StorageConnectorSecretkeyMaxLength;
  }
  public FeaturestoreClientSettingsDTO s3IAMRole(Boolean s3IAMRole) {
    this.s3IAMRole = s3IAMRole;
    return this;
  }

  

  /**
  * Get s3IAMRole
  * @return s3IAMRole
  **/
  @Schema(description = "")
  public Boolean isS3IAMRole() {
    return s3IAMRole;
  }
  public void setS3IAMRole(Boolean s3IAMRole) {
    this.s3IAMRole = s3IAMRole;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupNameMaxLength(Integer cachedFeaturegroupNameMaxLength) {
    this.cachedFeaturegroupNameMaxLength = cachedFeaturegroupNameMaxLength;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupNameMaxLength
  * @return cachedFeaturegroupNameMaxLength
  **/
  @Schema(description = "")
  public Integer getCachedFeaturegroupNameMaxLength() {
    return cachedFeaturegroupNameMaxLength;
  }
  public void setCachedFeaturegroupNameMaxLength(Integer cachedFeaturegroupNameMaxLength) {
    this.cachedFeaturegroupNameMaxLength = cachedFeaturegroupNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupDescriptionMaxLength(Integer cachedFeaturegroupDescriptionMaxLength) {
    this.cachedFeaturegroupDescriptionMaxLength = cachedFeaturegroupDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupDescriptionMaxLength
  * @return cachedFeaturegroupDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getCachedFeaturegroupDescriptionMaxLength() {
    return cachedFeaturegroupDescriptionMaxLength;
  }
  public void setCachedFeaturegroupDescriptionMaxLength(Integer cachedFeaturegroupDescriptionMaxLength) {
    this.cachedFeaturegroupDescriptionMaxLength = cachedFeaturegroupDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupFeatureNameMaxLength(Integer cachedFeaturegroupFeatureNameMaxLength) {
    this.cachedFeaturegroupFeatureNameMaxLength = cachedFeaturegroupFeatureNameMaxLength;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupFeatureNameMaxLength
  * @return cachedFeaturegroupFeatureNameMaxLength
  **/
  @Schema(description = "")
  public Integer getCachedFeaturegroupFeatureNameMaxLength() {
    return cachedFeaturegroupFeatureNameMaxLength;
  }
  public void setCachedFeaturegroupFeatureNameMaxLength(Integer cachedFeaturegroupFeatureNameMaxLength) {
    this.cachedFeaturegroupFeatureNameMaxLength = cachedFeaturegroupFeatureNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupFeatureDescriptionMaxLength(Integer cachedFeaturegroupFeatureDescriptionMaxLength) {
    this.cachedFeaturegroupFeatureDescriptionMaxLength = cachedFeaturegroupFeatureDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupFeatureDescriptionMaxLength
  * @return cachedFeaturegroupFeatureDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getCachedFeaturegroupFeatureDescriptionMaxLength() {
    return cachedFeaturegroupFeatureDescriptionMaxLength;
  }
  public void setCachedFeaturegroupFeatureDescriptionMaxLength(Integer cachedFeaturegroupFeatureDescriptionMaxLength) {
    this.cachedFeaturegroupFeatureDescriptionMaxLength = cachedFeaturegroupFeatureDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupNameMaxLength(Integer onDemandFeaturegroupNameMaxLength) {
    this.onDemandFeaturegroupNameMaxLength = onDemandFeaturegroupNameMaxLength;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupNameMaxLength
  * @return onDemandFeaturegroupNameMaxLength
  **/
  @Schema(description = "")
  public Integer getOnDemandFeaturegroupNameMaxLength() {
    return onDemandFeaturegroupNameMaxLength;
  }
  public void setOnDemandFeaturegroupNameMaxLength(Integer onDemandFeaturegroupNameMaxLength) {
    this.onDemandFeaturegroupNameMaxLength = onDemandFeaturegroupNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupDescriptionMaxLength(Integer onDemandFeaturegroupDescriptionMaxLength) {
    this.onDemandFeaturegroupDescriptionMaxLength = onDemandFeaturegroupDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupDescriptionMaxLength
  * @return onDemandFeaturegroupDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getOnDemandFeaturegroupDescriptionMaxLength() {
    return onDemandFeaturegroupDescriptionMaxLength;
  }
  public void setOnDemandFeaturegroupDescriptionMaxLength(Integer onDemandFeaturegroupDescriptionMaxLength) {
    this.onDemandFeaturegroupDescriptionMaxLength = onDemandFeaturegroupDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupFeatureNameMaxLength(Integer onDemandFeaturegroupFeatureNameMaxLength) {
    this.onDemandFeaturegroupFeatureNameMaxLength = onDemandFeaturegroupFeatureNameMaxLength;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupFeatureNameMaxLength
  * @return onDemandFeaturegroupFeatureNameMaxLength
  **/
  @Schema(description = "")
  public Integer getOnDemandFeaturegroupFeatureNameMaxLength() {
    return onDemandFeaturegroupFeatureNameMaxLength;
  }
  public void setOnDemandFeaturegroupFeatureNameMaxLength(Integer onDemandFeaturegroupFeatureNameMaxLength) {
    this.onDemandFeaturegroupFeatureNameMaxLength = onDemandFeaturegroupFeatureNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupFeatureDescriptionMaxLength(Integer onDemandFeaturegroupFeatureDescriptionMaxLength) {
    this.onDemandFeaturegroupFeatureDescriptionMaxLength = onDemandFeaturegroupFeatureDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupFeatureDescriptionMaxLength
  * @return onDemandFeaturegroupFeatureDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getOnDemandFeaturegroupFeatureDescriptionMaxLength() {
    return onDemandFeaturegroupFeatureDescriptionMaxLength;
  }
  public void setOnDemandFeaturegroupFeatureDescriptionMaxLength(Integer onDemandFeaturegroupFeatureDescriptionMaxLength) {
    this.onDemandFeaturegroupFeatureDescriptionMaxLength = onDemandFeaturegroupFeatureDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupSqlQueryMaxLength(Integer onDemandFeaturegroupSqlQueryMaxLength) {
    this.onDemandFeaturegroupSqlQueryMaxLength = onDemandFeaturegroupSqlQueryMaxLength;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupSqlQueryMaxLength
  * @return onDemandFeaturegroupSqlQueryMaxLength
  **/
  @Schema(description = "")
  public Integer getOnDemandFeaturegroupSqlQueryMaxLength() {
    return onDemandFeaturegroupSqlQueryMaxLength;
  }
  public void setOnDemandFeaturegroupSqlQueryMaxLength(Integer onDemandFeaturegroupSqlQueryMaxLength) {
    this.onDemandFeaturegroupSqlQueryMaxLength = onDemandFeaturegroupSqlQueryMaxLength;
  }
  public FeaturestoreClientSettingsDTO trainingDatasetDataFormats(List<String> trainingDatasetDataFormats) {
    this.trainingDatasetDataFormats = trainingDatasetDataFormats;
    return this;
  }

  public FeaturestoreClientSettingsDTO addTrainingDatasetDataFormatsItem(String trainingDatasetDataFormatsItem) {
    if (this.trainingDatasetDataFormats == null) {
      this.trainingDatasetDataFormats = new ArrayList<String>();
    }
    this.trainingDatasetDataFormats.add(trainingDatasetDataFormatsItem);
    return this;
  }

  /**
  * Get trainingDatasetDataFormats
  * @return trainingDatasetDataFormats
  **/
  @Schema(description = "")
  public List<String> getTrainingDatasetDataFormats() {
    return trainingDatasetDataFormats;
  }
  public void setTrainingDatasetDataFormats(List<String> trainingDatasetDataFormats) {
    this.trainingDatasetDataFormats = trainingDatasetDataFormats;
  }
  public FeaturestoreClientSettingsDTO externalTrainingDatasetNameMaxLength(Integer externalTrainingDatasetNameMaxLength) {
    this.externalTrainingDatasetNameMaxLength = externalTrainingDatasetNameMaxLength;
    return this;
  }

  

  /**
  * Get externalTrainingDatasetNameMaxLength
  * @return externalTrainingDatasetNameMaxLength
  **/
  @Schema(description = "")
  public Integer getExternalTrainingDatasetNameMaxLength() {
    return externalTrainingDatasetNameMaxLength;
  }
  public void setExternalTrainingDatasetNameMaxLength(Integer externalTrainingDatasetNameMaxLength) {
    this.externalTrainingDatasetNameMaxLength = externalTrainingDatasetNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO hopsfsTrainingDatasetNameMaxLength(Integer hopsfsTrainingDatasetNameMaxLength) {
    this.hopsfsTrainingDatasetNameMaxLength = hopsfsTrainingDatasetNameMaxLength;
    return this;
  }

  

  /**
  * Get hopsfsTrainingDatasetNameMaxLength
  * @return hopsfsTrainingDatasetNameMaxLength
  **/
  @Schema(description = "")
  public Integer getHopsfsTrainingDatasetNameMaxLength() {
    return hopsfsTrainingDatasetNameMaxLength;
  }
  public void setHopsfsTrainingDatasetNameMaxLength(Integer hopsfsTrainingDatasetNameMaxLength) {
    this.hopsfsTrainingDatasetNameMaxLength = hopsfsTrainingDatasetNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO trainingDatasetFeatureNameMaxLength(Integer trainingDatasetFeatureNameMaxLength) {
    this.trainingDatasetFeatureNameMaxLength = trainingDatasetFeatureNameMaxLength;
    return this;
  }

  

  /**
  * Get trainingDatasetFeatureNameMaxLength
  * @return trainingDatasetFeatureNameMaxLength
  **/
  @Schema(description = "")
  public Integer getTrainingDatasetFeatureNameMaxLength() {
    return trainingDatasetFeatureNameMaxLength;
  }
  public void setTrainingDatasetFeatureNameMaxLength(Integer trainingDatasetFeatureNameMaxLength) {
    this.trainingDatasetFeatureNameMaxLength = trainingDatasetFeatureNameMaxLength;
  }
  public FeaturestoreClientSettingsDTO trainingDatasetFeatureDescriptionMaxLength(Integer trainingDatasetFeatureDescriptionMaxLength) {
    this.trainingDatasetFeatureDescriptionMaxLength = trainingDatasetFeatureDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get trainingDatasetFeatureDescriptionMaxLength
  * @return trainingDatasetFeatureDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getTrainingDatasetFeatureDescriptionMaxLength() {
    return trainingDatasetFeatureDescriptionMaxLength;
  }
  public void setTrainingDatasetFeatureDescriptionMaxLength(Integer trainingDatasetFeatureDescriptionMaxLength) {
    this.trainingDatasetFeatureDescriptionMaxLength = trainingDatasetFeatureDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupType(String onDemandFeaturegroupType) {
    this.onDemandFeaturegroupType = onDemandFeaturegroupType;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupType
  * @return onDemandFeaturegroupType
  **/
  @Schema(description = "")
  public String getOnDemandFeaturegroupType() {
    return onDemandFeaturegroupType;
  }
  public void setOnDemandFeaturegroupType(String onDemandFeaturegroupType) {
    this.onDemandFeaturegroupType = onDemandFeaturegroupType;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupType(String cachedFeaturegroupType) {
    this.cachedFeaturegroupType = cachedFeaturegroupType;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupType
  * @return cachedFeaturegroupType
  **/
  @Schema(description = "")
  public String getCachedFeaturegroupType() {
    return cachedFeaturegroupType;
  }
  public void setCachedFeaturegroupType(String cachedFeaturegroupType) {
    this.cachedFeaturegroupType = cachedFeaturegroupType;
  }
  public FeaturestoreClientSettingsDTO jdbcConnectorType(String jdbcConnectorType) {
    this.jdbcConnectorType = jdbcConnectorType;
    return this;
  }

  

  /**
  * Get jdbcConnectorType
  * @return jdbcConnectorType
  **/
  @Schema(description = "")
  public String getJdbcConnectorType() {
    return jdbcConnectorType;
  }
  public void setJdbcConnectorType(String jdbcConnectorType) {
    this.jdbcConnectorType = jdbcConnectorType;
  }
  public FeaturestoreClientSettingsDTO hopsfsConnectorType(String hopsfsConnectorType) {
    this.hopsfsConnectorType = hopsfsConnectorType;
    return this;
  }

  

  /**
  * Get hopsfsConnectorType
  * @return hopsfsConnectorType
  **/
  @Schema(description = "")
  public String getHopsfsConnectorType() {
    return hopsfsConnectorType;
  }
  public void setHopsfsConnectorType(String hopsfsConnectorType) {
    this.hopsfsConnectorType = hopsfsConnectorType;
  }
  public FeaturestoreClientSettingsDTO s3ConnectorType(String s3ConnectorType) {
    this.s3ConnectorType = s3ConnectorType;
    return this;
  }

  

  /**
  * Get s3ConnectorType
  * @return s3ConnectorType
  **/
  @Schema(description = "")
  public String getS3ConnectorType() {
    return s3ConnectorType;
  }
  public void setS3ConnectorType(String s3ConnectorType) {
    this.s3ConnectorType = s3ConnectorType;
  }
  public FeaturestoreClientSettingsDTO cachedFeaturegroupDtoType(String cachedFeaturegroupDtoType) {
    this.cachedFeaturegroupDtoType = cachedFeaturegroupDtoType;
    return this;
  }

  

  /**
  * Get cachedFeaturegroupDtoType
  * @return cachedFeaturegroupDtoType
  **/
  @Schema(description = "")
  public String getCachedFeaturegroupDtoType() {
    return cachedFeaturegroupDtoType;
  }
  public void setCachedFeaturegroupDtoType(String cachedFeaturegroupDtoType) {
    this.cachedFeaturegroupDtoType = cachedFeaturegroupDtoType;
  }
  public FeaturestoreClientSettingsDTO onDemandFeaturegroupDtoType(String onDemandFeaturegroupDtoType) {
    this.onDemandFeaturegroupDtoType = onDemandFeaturegroupDtoType;
    return this;
  }

  

  /**
  * Get onDemandFeaturegroupDtoType
  * @return onDemandFeaturegroupDtoType
  **/
  @Schema(description = "")
  public String getOnDemandFeaturegroupDtoType() {
    return onDemandFeaturegroupDtoType;
  }
  public void setOnDemandFeaturegroupDtoType(String onDemandFeaturegroupDtoType) {
    this.onDemandFeaturegroupDtoType = onDemandFeaturegroupDtoType;
  }
  public FeaturestoreClientSettingsDTO hopsfsTrainingDatasetType(String hopsfsTrainingDatasetType) {
    this.hopsfsTrainingDatasetType = hopsfsTrainingDatasetType;
    return this;
  }

  

  /**
  * Get hopsfsTrainingDatasetType
  * @return hopsfsTrainingDatasetType
  **/
  @Schema(description = "")
  public String getHopsfsTrainingDatasetType() {
    return hopsfsTrainingDatasetType;
  }
  public void setHopsfsTrainingDatasetType(String hopsfsTrainingDatasetType) {
    this.hopsfsTrainingDatasetType = hopsfsTrainingDatasetType;
  }
  public FeaturestoreClientSettingsDTO externalTrainingDatasetType(String externalTrainingDatasetType) {
    this.externalTrainingDatasetType = externalTrainingDatasetType;
    return this;
  }

  

  /**
  * Get externalTrainingDatasetType
  * @return externalTrainingDatasetType
  **/
  @Schema(description = "")
  public String getExternalTrainingDatasetType() {
    return externalTrainingDatasetType;
  }
  public void setExternalTrainingDatasetType(String externalTrainingDatasetType) {
    this.externalTrainingDatasetType = externalTrainingDatasetType;
  }
  public FeaturestoreClientSettingsDTO hopsfsTrainingDatasetDtoType(String hopsfsTrainingDatasetDtoType) {
    this.hopsfsTrainingDatasetDtoType = hopsfsTrainingDatasetDtoType;
    return this;
  }

  

  /**
  * Get hopsfsTrainingDatasetDtoType
  * @return hopsfsTrainingDatasetDtoType
  **/
  @Schema(description = "")
  public String getHopsfsTrainingDatasetDtoType() {
    return hopsfsTrainingDatasetDtoType;
  }
  public void setHopsfsTrainingDatasetDtoType(String hopsfsTrainingDatasetDtoType) {
    this.hopsfsTrainingDatasetDtoType = hopsfsTrainingDatasetDtoType;
  }
  public FeaturestoreClientSettingsDTO externalTrainingDatasetDtoType(String externalTrainingDatasetDtoType) {
    this.externalTrainingDatasetDtoType = externalTrainingDatasetDtoType;
    return this;
  }

  

  /**
  * Get externalTrainingDatasetDtoType
  * @return externalTrainingDatasetDtoType
  **/
  @Schema(description = "")
  public String getExternalTrainingDatasetDtoType() {
    return externalTrainingDatasetDtoType;
  }
  public void setExternalTrainingDatasetDtoType(String externalTrainingDatasetDtoType) {
    this.externalTrainingDatasetDtoType = externalTrainingDatasetDtoType;
  }
  public FeaturestoreClientSettingsDTO trainingDatasetDescriptionMaxLength(Integer trainingDatasetDescriptionMaxLength) {
    this.trainingDatasetDescriptionMaxLength = trainingDatasetDescriptionMaxLength;
    return this;
  }

  

  /**
  * Get trainingDatasetDescriptionMaxLength
  * @return trainingDatasetDescriptionMaxLength
  **/
  @Schema(description = "")
  public Integer getTrainingDatasetDescriptionMaxLength() {
    return trainingDatasetDescriptionMaxLength;
  }
  public void setTrainingDatasetDescriptionMaxLength(Integer trainingDatasetDescriptionMaxLength) {
    this.trainingDatasetDescriptionMaxLength = trainingDatasetDescriptionMaxLength;
  }
  public FeaturestoreClientSettingsDTO s3ConnectorDtoType(String s3ConnectorDtoType) {
    this.s3ConnectorDtoType = s3ConnectorDtoType;
    return this;
  }

  

  /**
  * Get s3ConnectorDtoType
  * @return s3ConnectorDtoType
  **/
  @Schema(description = "")
  public String getS3ConnectorDtoType() {
    return s3ConnectorDtoType;
  }
  public void setS3ConnectorDtoType(String s3ConnectorDtoType) {
    this.s3ConnectorDtoType = s3ConnectorDtoType;
  }
  public FeaturestoreClientSettingsDTO jdbcConnectorDtoType(String jdbcConnectorDtoType) {
    this.jdbcConnectorDtoType = jdbcConnectorDtoType;
    return this;
  }

  

  /**
  * Get jdbcConnectorDtoType
  * @return jdbcConnectorDtoType
  **/
  @Schema(description = "")
  public String getJdbcConnectorDtoType() {
    return jdbcConnectorDtoType;
  }
  public void setJdbcConnectorDtoType(String jdbcConnectorDtoType) {
    this.jdbcConnectorDtoType = jdbcConnectorDtoType;
  }
  public FeaturestoreClientSettingsDTO hopsfsConnectorDtoType(String hopsfsConnectorDtoType) {
    this.hopsfsConnectorDtoType = hopsfsConnectorDtoType;
    return this;
  }

  

  /**
  * Get hopsfsConnectorDtoType
  * @return hopsfsConnectorDtoType
  **/
  @Schema(description = "")
  public String getHopsfsConnectorDtoType() {
    return hopsfsConnectorDtoType;
  }
  public void setHopsfsConnectorDtoType(String hopsfsConnectorDtoType) {
    this.hopsfsConnectorDtoType = hopsfsConnectorDtoType;
  }
  public FeaturestoreClientSettingsDTO featuregroupType(String featuregroupType) {
    this.featuregroupType = featuregroupType;
    return this;
  }

  

  /**
  * Get featuregroupType
  * @return featuregroupType
  **/
  @Schema(description = "")
  public String getFeaturegroupType() {
    return featuregroupType;
  }
  public void setFeaturegroupType(String featuregroupType) {
    this.featuregroupType = featuregroupType;
  }
  public FeaturestoreClientSettingsDTO trainingDatasetType(String trainingDatasetType) {
    this.trainingDatasetType = trainingDatasetType;
    return this;
  }

  

  /**
  * Get trainingDatasetType
  * @return trainingDatasetType
  **/
  @Schema(description = "")
  public String getTrainingDatasetType() {
    return trainingDatasetType;
  }
  public void setTrainingDatasetType(String trainingDatasetType) {
    this.trainingDatasetType = trainingDatasetType;
  }
  public FeaturestoreClientSettingsDTO suggestedHiveFeatureTypes(List<String> suggestedHiveFeatureTypes) {
    this.suggestedHiveFeatureTypes = suggestedHiveFeatureTypes;
    return this;
  }

  public FeaturestoreClientSettingsDTO addSuggestedHiveFeatureTypesItem(String suggestedHiveFeatureTypesItem) {
    if (this.suggestedHiveFeatureTypes == null) {
      this.suggestedHiveFeatureTypes = new ArrayList<String>();
    }
    this.suggestedHiveFeatureTypes.add(suggestedHiveFeatureTypesItem);
    return this;
  }

  /**
  * Get suggestedHiveFeatureTypes
  * @return suggestedHiveFeatureTypes
  **/
  @Schema(description = "")
  public List<String> getSuggestedHiveFeatureTypes() {
    return suggestedHiveFeatureTypes;
  }
  public void setSuggestedHiveFeatureTypes(List<String> suggestedHiveFeatureTypes) {
    this.suggestedHiveFeatureTypes = suggestedHiveFeatureTypes;
  }
  public FeaturestoreClientSettingsDTO featurestoreUtil4jMainClass(String featurestoreUtil4jMainClass) {
    this.featurestoreUtil4jMainClass = featurestoreUtil4jMainClass;
    return this;
  }

  

  /**
  * Get featurestoreUtil4jMainClass
  * @return featurestoreUtil4jMainClass
  **/
  @Schema(description = "")
  public String getFeaturestoreUtil4jMainClass() {
    return featurestoreUtil4jMainClass;
  }
  public void setFeaturestoreUtil4jMainClass(String featurestoreUtil4jMainClass) {
    this.featurestoreUtil4jMainClass = featurestoreUtil4jMainClass;
  }
  public FeaturestoreClientSettingsDTO featurestoreUtil4jArgsDataset(String featurestoreUtil4jArgsDataset) {
    this.featurestoreUtil4jArgsDataset = featurestoreUtil4jArgsDataset;
    return this;
  }

  

  /**
  * Get featurestoreUtil4jArgsDataset
  * @return featurestoreUtil4jArgsDataset
  **/
  @Schema(description = "")
  public String getFeaturestoreUtil4jArgsDataset() {
    return featurestoreUtil4jArgsDataset;
  }
  public void setFeaturestoreUtil4jArgsDataset(String featurestoreUtil4jArgsDataset) {
    this.featurestoreUtil4jArgsDataset = featurestoreUtil4jArgsDataset;
  }
  public FeaturestoreClientSettingsDTO featurestoreUtilPythonMainClass(String featurestoreUtilPythonMainClass) {
    this.featurestoreUtilPythonMainClass = featurestoreUtilPythonMainClass;
    return this;
  }

  

  /**
  * Get featurestoreUtilPythonMainClass
  * @return featurestoreUtilPythonMainClass
  **/
  @Schema(description = "")
  public String getFeaturestoreUtilPythonMainClass() {
    return featurestoreUtilPythonMainClass;
  }
  public void setFeaturestoreUtilPythonMainClass(String featurestoreUtilPythonMainClass) {
    this.featurestoreUtilPythonMainClass = featurestoreUtilPythonMainClass;
  }
  public FeaturestoreClientSettingsDTO featurestoreUtil4jExecutable(String featurestoreUtil4jExecutable) {
    this.featurestoreUtil4jExecutable = featurestoreUtil4jExecutable;
    return this;
  }

  

  /**
  * Get featurestoreUtil4jExecutable
  * @return featurestoreUtil4jExecutable
  **/
  @Schema(description = "")
  public String getFeaturestoreUtil4jExecutable() {
    return featurestoreUtil4jExecutable;
  }
  public void setFeaturestoreUtil4jExecutable(String featurestoreUtil4jExecutable) {
    this.featurestoreUtil4jExecutable = featurestoreUtil4jExecutable;
  }
  public FeaturestoreClientSettingsDTO featurestoreUtilPythonExecutable(String featurestoreUtilPythonExecutable) {
    this.featurestoreUtilPythonExecutable = featurestoreUtilPythonExecutable;
    return this;
  }

  

  /**
  * Get featurestoreUtilPythonExecutable
  * @return featurestoreUtilPythonExecutable
  **/
  @Schema(description = "")
  public String getFeaturestoreUtilPythonExecutable() {
    return featurestoreUtilPythonExecutable;
  }
  public void setFeaturestoreUtilPythonExecutable(String featurestoreUtilPythonExecutable) {
    this.featurestoreUtilPythonExecutable = featurestoreUtilPythonExecutable;
  }
  public FeaturestoreClientSettingsDTO s3BucketTrainingDatasetsFolder(String s3BucketTrainingDatasetsFolder) {
    this.s3BucketTrainingDatasetsFolder = s3BucketTrainingDatasetsFolder;
    return this;
  }

  

  /**
  * Get s3BucketTrainingDatasetsFolder
  * @return s3BucketTrainingDatasetsFolder
  **/
  @Schema(description = "")
  public String getS3BucketTrainingDatasetsFolder() {
    return s3BucketTrainingDatasetsFolder;
  }
  public void setS3BucketTrainingDatasetsFolder(String s3BucketTrainingDatasetsFolder) {
    this.s3BucketTrainingDatasetsFolder = s3BucketTrainingDatasetsFolder;
  }
  public FeaturestoreClientSettingsDTO featureImportConnectors(List<String> featureImportConnectors) {
    this.featureImportConnectors = featureImportConnectors;
    return this;
  }

  public FeaturestoreClientSettingsDTO addFeatureImportConnectorsItem(String featureImportConnectorsItem) {
    if (this.featureImportConnectors == null) {
      this.featureImportConnectors = new ArrayList<String>();
    }
    this.featureImportConnectors.add(featureImportConnectorsItem);
    return this;
  }

  /**
  * Get featureImportConnectors
  * @return featureImportConnectors
  **/
  @Schema(description = "")
  public List<String> getFeatureImportConnectors() {
    return featureImportConnectors;
  }
  public void setFeatureImportConnectors(List<String> featureImportConnectors) {
    this.featureImportConnectors = featureImportConnectors;
  }
  public FeaturestoreClientSettingsDTO onlineFeaturestoreEnabled(Boolean onlineFeaturestoreEnabled) {
    this.onlineFeaturestoreEnabled = onlineFeaturestoreEnabled;
    return this;
  }

  

  /**
  * Get onlineFeaturestoreEnabled
  * @return onlineFeaturestoreEnabled
  **/
  @Schema(description = "")
  public Boolean isOnlineFeaturestoreEnabled() {
    return onlineFeaturestoreEnabled;
  }
  public void setOnlineFeaturestoreEnabled(Boolean onlineFeaturestoreEnabled) {
    this.onlineFeaturestoreEnabled = onlineFeaturestoreEnabled;
  }
  public FeaturestoreClientSettingsDTO suggestedMysqlFeatureTypes(List<String> suggestedMysqlFeatureTypes) {
    this.suggestedMysqlFeatureTypes = suggestedMysqlFeatureTypes;
    return this;
  }

  public FeaturestoreClientSettingsDTO addSuggestedMysqlFeatureTypesItem(String suggestedMysqlFeatureTypesItem) {
    if (this.suggestedMysqlFeatureTypes == null) {
      this.suggestedMysqlFeatureTypes = new ArrayList<String>();
    }
    this.suggestedMysqlFeatureTypes.add(suggestedMysqlFeatureTypesItem);
    return this;
  }

  /**
  * Get suggestedMysqlFeatureTypes
  * @return suggestedMysqlFeatureTypes
  **/
  @Schema(description = "")
  public List<String> getSuggestedMysqlFeatureTypes() {
    return suggestedMysqlFeatureTypes;
  }
  public void setSuggestedMysqlFeatureTypes(List<String> suggestedMysqlFeatureTypes) {
    this.suggestedMysqlFeatureTypes = suggestedMysqlFeatureTypes;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeaturestoreClientSettingsDTO featurestoreClientSettingsDTO = (FeaturestoreClientSettingsDTO) o;
    return Objects.equals(this.featurestoreStatisticsMaxCorrelations, featurestoreClientSettingsDTO.featurestoreStatisticsMaxCorrelations) &&
        Objects.equals(this.featurestoreRegex, featurestoreClientSettingsDTO.featurestoreRegex) &&
        Objects.equals(this.storageConnectorNameMaxLength, featurestoreClientSettingsDTO.storageConnectorNameMaxLength) &&
        Objects.equals(this.storageConnectorDescriptionMaxLength, featurestoreClientSettingsDTO.storageConnectorDescriptionMaxLength) &&
        Objects.equals(this.jdbcStorageConnectorConnectionstringMaxLength, featurestoreClientSettingsDTO.jdbcStorageConnectorConnectionstringMaxLength) &&
        Objects.equals(this.jdbcStorageConnectorArgumentsMaxLength, featurestoreClientSettingsDTO.jdbcStorageConnectorArgumentsMaxLength) &&
        Objects.equals(this.s3StorageConnectorBucketMaxLength, featurestoreClientSettingsDTO.s3StorageConnectorBucketMaxLength) &&
        Objects.equals(this.s3StorageConnectorAccesskeyMaxLength, featurestoreClientSettingsDTO.s3StorageConnectorAccesskeyMaxLength) &&
        Objects.equals(this.s3StorageConnectorSecretkeyMaxLength, featurestoreClientSettingsDTO.s3StorageConnectorSecretkeyMaxLength) &&
        Objects.equals(this.s3IAMRole, featurestoreClientSettingsDTO.s3IAMRole) &&
        Objects.equals(this.cachedFeaturegroupNameMaxLength, featurestoreClientSettingsDTO.cachedFeaturegroupNameMaxLength) &&
        Objects.equals(this.cachedFeaturegroupDescriptionMaxLength, featurestoreClientSettingsDTO.cachedFeaturegroupDescriptionMaxLength) &&
        Objects.equals(this.cachedFeaturegroupFeatureNameMaxLength, featurestoreClientSettingsDTO.cachedFeaturegroupFeatureNameMaxLength) &&
        Objects.equals(this.cachedFeaturegroupFeatureDescriptionMaxLength, featurestoreClientSettingsDTO.cachedFeaturegroupFeatureDescriptionMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupNameMaxLength, featurestoreClientSettingsDTO.onDemandFeaturegroupNameMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupDescriptionMaxLength, featurestoreClientSettingsDTO.onDemandFeaturegroupDescriptionMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupFeatureNameMaxLength, featurestoreClientSettingsDTO.onDemandFeaturegroupFeatureNameMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupFeatureDescriptionMaxLength, featurestoreClientSettingsDTO.onDemandFeaturegroupFeatureDescriptionMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupSqlQueryMaxLength, featurestoreClientSettingsDTO.onDemandFeaturegroupSqlQueryMaxLength) &&
        Objects.equals(this.trainingDatasetDataFormats, featurestoreClientSettingsDTO.trainingDatasetDataFormats) &&
        Objects.equals(this.externalTrainingDatasetNameMaxLength, featurestoreClientSettingsDTO.externalTrainingDatasetNameMaxLength) &&
        Objects.equals(this.hopsfsTrainingDatasetNameMaxLength, featurestoreClientSettingsDTO.hopsfsTrainingDatasetNameMaxLength) &&
        Objects.equals(this.trainingDatasetFeatureNameMaxLength, featurestoreClientSettingsDTO.trainingDatasetFeatureNameMaxLength) &&
        Objects.equals(this.trainingDatasetFeatureDescriptionMaxLength, featurestoreClientSettingsDTO.trainingDatasetFeatureDescriptionMaxLength) &&
        Objects.equals(this.onDemandFeaturegroupType, featurestoreClientSettingsDTO.onDemandFeaturegroupType) &&
        Objects.equals(this.cachedFeaturegroupType, featurestoreClientSettingsDTO.cachedFeaturegroupType) &&
        Objects.equals(this.jdbcConnectorType, featurestoreClientSettingsDTO.jdbcConnectorType) &&
        Objects.equals(this.hopsfsConnectorType, featurestoreClientSettingsDTO.hopsfsConnectorType) &&
        Objects.equals(this.s3ConnectorType, featurestoreClientSettingsDTO.s3ConnectorType) &&
        Objects.equals(this.cachedFeaturegroupDtoType, featurestoreClientSettingsDTO.cachedFeaturegroupDtoType) &&
        Objects.equals(this.onDemandFeaturegroupDtoType, featurestoreClientSettingsDTO.onDemandFeaturegroupDtoType) &&
        Objects.equals(this.hopsfsTrainingDatasetType, featurestoreClientSettingsDTO.hopsfsTrainingDatasetType) &&
        Objects.equals(this.externalTrainingDatasetType, featurestoreClientSettingsDTO.externalTrainingDatasetType) &&
        Objects.equals(this.hopsfsTrainingDatasetDtoType, featurestoreClientSettingsDTO.hopsfsTrainingDatasetDtoType) &&
        Objects.equals(this.externalTrainingDatasetDtoType, featurestoreClientSettingsDTO.externalTrainingDatasetDtoType) &&
        Objects.equals(this.trainingDatasetDescriptionMaxLength, featurestoreClientSettingsDTO.trainingDatasetDescriptionMaxLength) &&
        Objects.equals(this.s3ConnectorDtoType, featurestoreClientSettingsDTO.s3ConnectorDtoType) &&
        Objects.equals(this.jdbcConnectorDtoType, featurestoreClientSettingsDTO.jdbcConnectorDtoType) &&
        Objects.equals(this.hopsfsConnectorDtoType, featurestoreClientSettingsDTO.hopsfsConnectorDtoType) &&
        Objects.equals(this.featuregroupType, featurestoreClientSettingsDTO.featuregroupType) &&
        Objects.equals(this.trainingDatasetType, featurestoreClientSettingsDTO.trainingDatasetType) &&
        Objects.equals(this.suggestedHiveFeatureTypes, featurestoreClientSettingsDTO.suggestedHiveFeatureTypes) &&
        Objects.equals(this.featurestoreUtil4jMainClass, featurestoreClientSettingsDTO.featurestoreUtil4jMainClass) &&
        Objects.equals(this.featurestoreUtil4jArgsDataset, featurestoreClientSettingsDTO.featurestoreUtil4jArgsDataset) &&
        Objects.equals(this.featurestoreUtilPythonMainClass, featurestoreClientSettingsDTO.featurestoreUtilPythonMainClass) &&
        Objects.equals(this.featurestoreUtil4jExecutable, featurestoreClientSettingsDTO.featurestoreUtil4jExecutable) &&
        Objects.equals(this.featurestoreUtilPythonExecutable, featurestoreClientSettingsDTO.featurestoreUtilPythonExecutable) &&
        Objects.equals(this.s3BucketTrainingDatasetsFolder, featurestoreClientSettingsDTO.s3BucketTrainingDatasetsFolder) &&
        Objects.equals(this.featureImportConnectors, featurestoreClientSettingsDTO.featureImportConnectors) &&
        Objects.equals(this.onlineFeaturestoreEnabled, featurestoreClientSettingsDTO.onlineFeaturestoreEnabled) &&
        Objects.equals(this.suggestedMysqlFeatureTypes, featurestoreClientSettingsDTO.suggestedMysqlFeatureTypes);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(featurestoreStatisticsMaxCorrelations, featurestoreRegex, storageConnectorNameMaxLength, storageConnectorDescriptionMaxLength, jdbcStorageConnectorConnectionstringMaxLength, jdbcStorageConnectorArgumentsMaxLength, s3StorageConnectorBucketMaxLength, s3StorageConnectorAccesskeyMaxLength, s3StorageConnectorSecretkeyMaxLength, s3IAMRole, cachedFeaturegroupNameMaxLength, cachedFeaturegroupDescriptionMaxLength, cachedFeaturegroupFeatureNameMaxLength, cachedFeaturegroupFeatureDescriptionMaxLength, onDemandFeaturegroupNameMaxLength, onDemandFeaturegroupDescriptionMaxLength, onDemandFeaturegroupFeatureNameMaxLength, onDemandFeaturegroupFeatureDescriptionMaxLength, onDemandFeaturegroupSqlQueryMaxLength, trainingDatasetDataFormats, externalTrainingDatasetNameMaxLength, hopsfsTrainingDatasetNameMaxLength, trainingDatasetFeatureNameMaxLength, trainingDatasetFeatureDescriptionMaxLength, onDemandFeaturegroupType, cachedFeaturegroupType, jdbcConnectorType, hopsfsConnectorType, s3ConnectorType, cachedFeaturegroupDtoType, onDemandFeaturegroupDtoType, hopsfsTrainingDatasetType, externalTrainingDatasetType, hopsfsTrainingDatasetDtoType, externalTrainingDatasetDtoType, trainingDatasetDescriptionMaxLength, s3ConnectorDtoType, jdbcConnectorDtoType, hopsfsConnectorDtoType, featuregroupType, trainingDatasetType, suggestedHiveFeatureTypes, featurestoreUtil4jMainClass, featurestoreUtil4jArgsDataset, featurestoreUtilPythonMainClass, featurestoreUtil4jExecutable, featurestoreUtilPythonExecutable, s3BucketTrainingDatasetsFolder, featureImportConnectors, onlineFeaturestoreEnabled, suggestedMysqlFeatureTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeaturestoreClientSettingsDTO {\n");
    
    sb.append("    featurestoreStatisticsMaxCorrelations: ").append(toIndentedString(featurestoreStatisticsMaxCorrelations)).append("\n");
    sb.append("    featurestoreRegex: ").append(toIndentedString(featurestoreRegex)).append("\n");
    sb.append("    storageConnectorNameMaxLength: ").append(toIndentedString(storageConnectorNameMaxLength)).append("\n");
    sb.append("    storageConnectorDescriptionMaxLength: ").append(toIndentedString(storageConnectorDescriptionMaxLength)).append("\n");
    sb.append("    jdbcStorageConnectorConnectionstringMaxLength: ").append(toIndentedString(jdbcStorageConnectorConnectionstringMaxLength)).append("\n");
    sb.append("    jdbcStorageConnectorArgumentsMaxLength: ").append(toIndentedString(jdbcStorageConnectorArgumentsMaxLength)).append("\n");
    sb.append("    s3StorageConnectorBucketMaxLength: ").append(toIndentedString(s3StorageConnectorBucketMaxLength)).append("\n");
    sb.append("    s3StorageConnectorAccesskeyMaxLength: ").append(toIndentedString(s3StorageConnectorAccesskeyMaxLength)).append("\n");
    sb.append("    s3StorageConnectorSecretkeyMaxLength: ").append(toIndentedString(s3StorageConnectorSecretkeyMaxLength)).append("\n");
    sb.append("    s3IAMRole: ").append(toIndentedString(s3IAMRole)).append("\n");
    sb.append("    cachedFeaturegroupNameMaxLength: ").append(toIndentedString(cachedFeaturegroupNameMaxLength)).append("\n");
    sb.append("    cachedFeaturegroupDescriptionMaxLength: ").append(toIndentedString(cachedFeaturegroupDescriptionMaxLength)).append("\n");
    sb.append("    cachedFeaturegroupFeatureNameMaxLength: ").append(toIndentedString(cachedFeaturegroupFeatureNameMaxLength)).append("\n");
    sb.append("    cachedFeaturegroupFeatureDescriptionMaxLength: ").append(toIndentedString(cachedFeaturegroupFeatureDescriptionMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupNameMaxLength: ").append(toIndentedString(onDemandFeaturegroupNameMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupDescriptionMaxLength: ").append(toIndentedString(onDemandFeaturegroupDescriptionMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupFeatureNameMaxLength: ").append(toIndentedString(onDemandFeaturegroupFeatureNameMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupFeatureDescriptionMaxLength: ").append(toIndentedString(onDemandFeaturegroupFeatureDescriptionMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupSqlQueryMaxLength: ").append(toIndentedString(onDemandFeaturegroupSqlQueryMaxLength)).append("\n");
    sb.append("    trainingDatasetDataFormats: ").append(toIndentedString(trainingDatasetDataFormats)).append("\n");
    sb.append("    externalTrainingDatasetNameMaxLength: ").append(toIndentedString(externalTrainingDatasetNameMaxLength)).append("\n");
    sb.append("    hopsfsTrainingDatasetNameMaxLength: ").append(toIndentedString(hopsfsTrainingDatasetNameMaxLength)).append("\n");
    sb.append("    trainingDatasetFeatureNameMaxLength: ").append(toIndentedString(trainingDatasetFeatureNameMaxLength)).append("\n");
    sb.append("    trainingDatasetFeatureDescriptionMaxLength: ").append(toIndentedString(trainingDatasetFeatureDescriptionMaxLength)).append("\n");
    sb.append("    onDemandFeaturegroupType: ").append(toIndentedString(onDemandFeaturegroupType)).append("\n");
    sb.append("    cachedFeaturegroupType: ").append(toIndentedString(cachedFeaturegroupType)).append("\n");
    sb.append("    jdbcConnectorType: ").append(toIndentedString(jdbcConnectorType)).append("\n");
    sb.append("    hopsfsConnectorType: ").append(toIndentedString(hopsfsConnectorType)).append("\n");
    sb.append("    s3ConnectorType: ").append(toIndentedString(s3ConnectorType)).append("\n");
    sb.append("    cachedFeaturegroupDtoType: ").append(toIndentedString(cachedFeaturegroupDtoType)).append("\n");
    sb.append("    onDemandFeaturegroupDtoType: ").append(toIndentedString(onDemandFeaturegroupDtoType)).append("\n");
    sb.append("    hopsfsTrainingDatasetType: ").append(toIndentedString(hopsfsTrainingDatasetType)).append("\n");
    sb.append("    externalTrainingDatasetType: ").append(toIndentedString(externalTrainingDatasetType)).append("\n");
    sb.append("    hopsfsTrainingDatasetDtoType: ").append(toIndentedString(hopsfsTrainingDatasetDtoType)).append("\n");
    sb.append("    externalTrainingDatasetDtoType: ").append(toIndentedString(externalTrainingDatasetDtoType)).append("\n");
    sb.append("    trainingDatasetDescriptionMaxLength: ").append(toIndentedString(trainingDatasetDescriptionMaxLength)).append("\n");
    sb.append("    s3ConnectorDtoType: ").append(toIndentedString(s3ConnectorDtoType)).append("\n");
    sb.append("    jdbcConnectorDtoType: ").append(toIndentedString(jdbcConnectorDtoType)).append("\n");
    sb.append("    hopsfsConnectorDtoType: ").append(toIndentedString(hopsfsConnectorDtoType)).append("\n");
    sb.append("    featuregroupType: ").append(toIndentedString(featuregroupType)).append("\n");
    sb.append("    trainingDatasetType: ").append(toIndentedString(trainingDatasetType)).append("\n");
    sb.append("    suggestedHiveFeatureTypes: ").append(toIndentedString(suggestedHiveFeatureTypes)).append("\n");
    sb.append("    featurestoreUtil4jMainClass: ").append(toIndentedString(featurestoreUtil4jMainClass)).append("\n");
    sb.append("    featurestoreUtil4jArgsDataset: ").append(toIndentedString(featurestoreUtil4jArgsDataset)).append("\n");
    sb.append("    featurestoreUtilPythonMainClass: ").append(toIndentedString(featurestoreUtilPythonMainClass)).append("\n");
    sb.append("    featurestoreUtil4jExecutable: ").append(toIndentedString(featurestoreUtil4jExecutable)).append("\n");
    sb.append("    featurestoreUtilPythonExecutable: ").append(toIndentedString(featurestoreUtilPythonExecutable)).append("\n");
    sb.append("    s3BucketTrainingDatasetsFolder: ").append(toIndentedString(s3BucketTrainingDatasetsFolder)).append("\n");
    sb.append("    featureImportConnectors: ").append(toIndentedString(featureImportConnectors)).append("\n");
    sb.append("    onlineFeaturestoreEnabled: ").append(toIndentedString(onlineFeaturestoreEnabled)).append("\n");
    sb.append("    suggestedMysqlFeatureTypes: ").append(toIndentedString(suggestedMysqlFeatureTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
