/*
 * Hopsworks api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UriBuilder;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Link
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-11-28T02:09:19.386+01:00[Europe/Stockholm]")public class Link {

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("uriBuilder")
  private UriBuilder uriBuilder = null;

  @SerializedName("rel")
  private String rel = null;

  @SerializedName("rels")
  private List<String> rels = null;

  @SerializedName("params")
  private Map<String, String> params = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("type")
  private String type = null;
  public Link uri(String uri) {
    this.uri = uri;
    return this;
  }

  

  /**
  * Get uri
  * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }
  public void setUri(String uri) {
    this.uri = uri;
  }
  public Link uriBuilder(UriBuilder uriBuilder) {
    this.uriBuilder = uriBuilder;
    return this;
  }

  

  /**
  * Get uriBuilder
  * @return uriBuilder
  **/
  @Schema(description = "")
  public UriBuilder getUriBuilder() {
    return uriBuilder;
  }
  public void setUriBuilder(UriBuilder uriBuilder) {
    this.uriBuilder = uriBuilder;
  }
  public Link rel(String rel) {
    this.rel = rel;
    return this;
  }

  

  /**
  * Get rel
  * @return rel
  **/
  @Schema(description = "")
  public String getRel() {
    return rel;
  }
  public void setRel(String rel) {
    this.rel = rel;
  }
  public Link rels(List<String> rels) {
    this.rels = rels;
    return this;
  }

  public Link addRelsItem(String relsItem) {
    if (this.rels == null) {
      this.rels = new ArrayList<String>();
    }
    this.rels.add(relsItem);
    return this;
  }

  /**
  * Get rels
  * @return rels
  **/
  @Schema(description = "")
  public List<String> getRels() {
    return rels;
  }
  public void setRels(List<String> rels) {
    this.rels = rels;
  }
  public Link params(Map<String, String> params) {
    this.params = params;
    return this;
  }

  
  public Link putParamsItem(String key, String paramsItem) {
    if (this.params == null) {
      this.params = new HashMap<String, String>();
    }
    this.params.put(key, paramsItem);
    return this;
  }
  /**
  * Get params
  * @return params
  **/
  @Schema(description = "")
  public Map<String, String> getParams() {
    return params;
  }
  public void setParams(Map<String, String> params) {
    this.params = params;
  }
  public Link title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public Link type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Link link = (Link) o;
    return Objects.equals(this.uri, link.uri) &&
        Objects.equals(this.uriBuilder, link.uriBuilder) &&
        Objects.equals(this.rel, link.rel) &&
        Objects.equals(this.rels, link.rels) &&
        Objects.equals(this.params, link.params) &&
        Objects.equals(this.title, link.title) &&
        Objects.equals(this.type, link.type);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(uri, uriBuilder, rel, rels, params, title, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Link {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    uriBuilder: ").append(toIndentedString(uriBuilder)).append("\n");
    sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
    sb.append("    rels: ").append(toIndentedString(rels)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
