export * from './admin.service';
import { AdminService } from './admin.service';
export * from './agentService.service';
import { AgentServiceService } from './agentService.service';
export * from './airflowRelatedEndpoints.service';
import { AirflowRelatedEndpointsService } from './airflowRelatedEndpoints.service';
export * from './apiKeyResource.service';
import { ApiKeyResourceService } from './apiKeyResource.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './bannerService.service';
import { BannerServiceService } from './bannerService.service';
export * from './clusterUtilisationService.service';
import { ClusterUtilisationServiceService } from './clusterUtilisationService.service';
export * from './crossDelaService.service';
import { CrossDelaServiceService } from './crossDelaService.service';
export * from './delaClusterProjectService.service';
import { DelaClusterProjectServiceService } from './delaClusterProjectService.service';
export * from './delaClusterService.service';
import { DelaClusterServiceService } from './delaClusterService.service';
export * from './delaService.service';
import { DelaServiceService } from './delaService.service';
export * from './elasticService.service';
import { ElasticServiceService } from './elasticService.service';
export * from './endpointService.service';
import { EndpointServiceService } from './endpointService.service';
export * from './featureStoreDataValidationService.service';
import { FeatureStoreDataValidationServiceService } from './featureStoreDataValidationService.service';
export * from './featuregroupService.service';
import { FeaturegroupServiceService } from './featuregroupService.service';
export * from './featurestoreService.service';
import { FeaturestoreServiceService } from './featurestoreService.service';
export * from './hopssiteService.service';
import { HopssiteServiceService } from './hopssiteService.service';
export * from './jWTService.service';
import { JWTServiceService } from './jWTService.service';
export * from './machineTypesResource.service';
import { MachineTypesResourceService } from './machineTypesResource.service';
export * from './maggyService.service';
import { MaggyServiceService } from './maggyService.service';
export * from './messageService.service';
import { MessageServiceService } from './messageService.service';
export * from './metadataService.service';
import { MetadataServiceService } from './metadataService.service';
export * from './modelInferenceService.service';
import { ModelInferenceServiceService } from './modelInferenceService.service';
export * from './monitorClusterService.service';
import { MonitorClusterServiceService } from './monitorClusterService.service';
export * from './projectActivitiesResource.service';
import { ProjectActivitiesResourceService } from './projectActivitiesResource.service';
export * from './projectService.service';
import { ProjectServiceService } from './projectService.service';
export * from './python.service';
import { PythonService } from './python.service';
export * from './pythonEnvironmentCommandsResource.service';
import { PythonEnvironmentCommandsResourceService } from './pythonEnvironmentCommandsResource.service';
export * from './pythonEnvironmentLibraryCommandsResource.service';
import { PythonEnvironmentLibraryCommandsResourceService } from './pythonEnvironmentLibraryCommandsResource.service';
export * from './pythonEnvironmentLibraryResource.service';
import { PythonEnvironmentLibraryResourceService } from './pythonEnvironmentLibraryResource.service';
export * from './pythonEnvironmentsResource.service';
import { PythonEnvironmentsResourceService } from './pythonEnvironmentsResource.service';
export * from './requestService.service';
import { RequestServiceService } from './requestService.service';
export * from './storageConnectorService.service';
import { StorageConnectorServiceService } from './storageConnectorService.service';
export * from './tensorFlowServingService.service';
import { TensorFlowServingServiceService } from './tensorFlowServingService.service';
export * from './trainingDatasetService.service';
import { TrainingDatasetServiceService } from './trainingDatasetService.service';
export * from './uIServingConfiguration.service';
import { UIServingConfigurationService } from './uIServingConfiguration.service';
export * from './userActivitiesResource.service';
import { UserActivitiesResourceService } from './userActivitiesResource.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './variablesService.service';
import { VariablesServiceService } from './variablesService.service';
export const APIS = [AdminService, AgentServiceService, AirflowRelatedEndpointsService, ApiKeyResourceService, AuthService, BannerServiceService, ClusterUtilisationServiceService, CrossDelaServiceService, DelaClusterProjectServiceService, DelaClusterServiceService, DelaServiceService, ElasticServiceService, EndpointServiceService, FeatureStoreDataValidationServiceService, FeaturegroupServiceService, FeaturestoreServiceService, HopssiteServiceService, JWTServiceService, MachineTypesResourceService, MaggyServiceService, MessageServiceService, MetadataServiceService, ModelInferenceServiceService, MonitorClusterServiceService, ProjectActivitiesResourceService, ProjectServiceService, PythonService, PythonEnvironmentCommandsResourceService, PythonEnvironmentLibraryCommandsResourceService, PythonEnvironmentLibraryResourceService, PythonEnvironmentsResourceService, RequestServiceService, StorageConnectorServiceService, TensorFlowServingServiceService, TrainingDatasetServiceService, UIServingConfigurationService, UserActivitiesResourceService, UsersService, VariablesServiceService];
