/**
 * Hopsworks api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CondaCommandsForKagentToExecuteOrReport { 
    /**
     * Operation to be performed
     */
    op: CondaCommandsForKagentToExecuteOrReport.OpEnum;
    /**
     * The user command will be executed
     */
    user?: string;
    /**
     * Name of the project the command is associated with
     */
    project: string;
    /**
     * ID of command
     */
    id: number;
    /**
     * Arguments passed to command
     */
    arg?: string;
    /**
     * Status of comamnd
     */
    status: CondaCommandsForKagentToExecuteOrReport.StatusEnum;
    /**
     * Python version to be enabled
     */
    version?: string;
    /**
     * Pip channel to download a library if not th default
     */
    channelUrl?: string;
    /**
     * Type of Conda installation
     */
    installType?: CondaCommandsForKagentToExecuteOrReport.InstallTypeEnum;
    /**
     * Name of the library to install
     */
    lib?: string;
    /**
     * Environment exported as a YML file
     */
    environmentYml?: string;
    /**
     * Whether or not to install Jupyter during the environment creation from a YML file
     */
    installJupyter?: boolean;
}
export namespace CondaCommandsForKagentToExecuteOrReport {
    export type OpEnum = 'CLONE' | 'CREATE' | 'BACKUP' | 'REMOVE' | 'LIST' | 'INSTALL' | 'UNINSTALL' | 'UPGRADE' | 'CLEAN' | 'YML';
    export const OpEnum = {
        CLONE: 'CLONE' as OpEnum,
        CREATE: 'CREATE' as OpEnum,
        BACKUP: 'BACKUP' as OpEnum,
        REMOVE: 'REMOVE' as OpEnum,
        LIST: 'LIST' as OpEnum,
        INSTALL: 'INSTALL' as OpEnum,
        UNINSTALL: 'UNINSTALL' as OpEnum,
        UPGRADE: 'UPGRADE' as OpEnum,
        CLEAN: 'CLEAN' as OpEnum,
        YML: 'YML' as OpEnum
    };
    export type StatusEnum = 'NEW' | 'SUCCESS' | 'ONGOING' | 'FAILED';
    export const StatusEnum = {
        NEW: 'NEW' as StatusEnum,
        SUCCESS: 'SUCCESS' as StatusEnum,
        ONGOING: 'ONGOING' as StatusEnum,
        FAILED: 'FAILED' as StatusEnum
    };
    export type InstallTypeEnum = 'ENVIRONMENT' | 'CONDA' | 'PIP';
    export const InstallTypeEnum = {
        ENVIRONMENT: 'ENVIRONMENT' as InstallTypeEnum,
        CONDA: 'CONDA' as InstallTypeEnum,
        PIP: 'PIP' as InstallTypeEnum
    };
}