/**
 * Hopsworks api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TopicDTO { 
    href?: string;
    items?: Array<TopicDTO>;
    count?: number;
    name?: string;
    numOfReplicas?: number;
    numOfPartitions?: number;
    schemaName?: string;
    schemaVersion?: number;
    ownerProjectId?: number;
    shared?: boolean;
}