# coding: utf-8

"""
    Hopsworks api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class HistogramBinDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bin': 'str',
        'frequency': 'int'
    }

    attribute_map = {
        'bin': 'bin',
        'frequency': 'frequency'
    }

    def __init__(self, bin=None, frequency=None):  # noqa: E501
        """HistogramBinDTO - a model defined in Swagger"""  # noqa: E501
        self._bin = None
        self._frequency = None
        self.discriminator = None
        if bin is not None:
            self.bin = bin
        if frequency is not None:
            self.frequency = frequency

    @property
    def bin(self):
        """Gets the bin of this HistogramBinDTO.  # noqa: E501


        :return: The bin of this HistogramBinDTO.  # noqa: E501
        :rtype: str
        """
        return self._bin

    @bin.setter
    def bin(self, bin):
        """Sets the bin of this HistogramBinDTO.


        :param bin: The bin of this HistogramBinDTO.  # noqa: E501
        :type: str
        """

        self._bin = bin

    @property
    def frequency(self):
        """Gets the frequency of this HistogramBinDTO.  # noqa: E501


        :return: The frequency of this HistogramBinDTO.  # noqa: E501
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this HistogramBinDTO.


        :param frequency: The frequency of this HistogramBinDTO.  # noqa: E501
        :type: int
        """

        self._frequency = frequency

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistogramBinDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistogramBinDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
